- repository: https://github.com/anthropics/skills
  ref: 0a64e398ec6bb34a494f0c347e8ccae53a862f8e # renovate: datasource=git-refs currentValue=main
  skills:
    - skills/doc-coauthoring
    - skills/skill-creator
- repository: https://github.com/anthropics/claude-code
  ref: 45bdfa96ca415da92e62b6ca85a1d6e29adf3c44 # renovate: datasource=git-refs currentValue=main
  skills:
    - plugins/frontend-design/skills/frontend-design
