- repository: https://github.com/anthropics/skills
  ref: 0a64e398ec6bb34a494f0c347e8ccae53a862f8e # renovate: datasource=git-refs currentValue=main
  skills:
    - skills/doc-coauthoring
    - skills/skill-creator
- repository: https://github.com/anthropics/claude-code
  ref: 5cfc0a1905ce0c0a9bd81d8a90fe6b62ff614357 # renovate: datasource=git-refs currentValue=main
  skills:
    - plugins/frontend-design/skills/frontend-design
