- repository: https://github.com/anthropics/skills
  ref: 12ab35c2eb5668c95810e6a6066f40f4218adc39 # renovate: datasource=git-refs currentValue=main
  skills:
    - skills/doc-coauthoring
    - skills/skill-creator
